remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
gem "github-pages", group: :jekyll_plugins

title: [Rusna Aida]
description: [Welcome to my GitHub portfolio! This repository showcases my work and projects. Feel free to explore, and don’t hesitate to reach out if you have any questions or collaboration opportunities.]
logo: Capture2.PNG
